#!/usr/bin/env bash
DOTFILES=${DOTFILES:-"$HOME/.dotfiles"}
[[ -d $DOTFILES ]] || { echo "Error: $DOTFILES does not exist"; exit 1; }

pushd "$DOTFILES" > /dev/null || exit
stow --restow */ || { echo "Error: Failed to stow directories"; exit 1; }
popd > /dev/null
echo "Stow complete."
